TugasKelompok_1/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('formulir/', include('donatur.urls')),
    path('penerima/', include('penerima.urls')),
    path('kritik-saran/', include('kritiksaran.urls')),
    path('testimoni/',include('testimoni.urls')),
   
]

donatur/urls.py
from django.urls import path
from . import views
from .views import *
from .views import formulir_donatur

app_name = 'donatur'

urlpatterns = [
    path('', views.formulir_donatur, name='formulir_donatur'),
    path('terimakasih/', views.terimakasih, name = 'terimakasih')
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.log_in, name='login'),
    path('logout/', views.log_out, name='logout'),
    path('signup/', views.signup, name='signup'),

]

penerima/urls.py
from django.urls import path

from . import views


app_name = 'penerima'

urlpatterns = [
    path('', views.pendaftar_form, name='pendaftar_form'),
    path('donatur/', views.display_form, name='display_form'),
    path('terimakasih/', views.thanks, name='thanks')
]

penerima/models.py
from django.db import models

# Create your models here.
class Formulir(models.Model):
    namalengkap= models.CharField(max_length=60)
    email = models.EmailField()
    pekerjaan = models.CharField(max_length=60)
    kota = models.CharField(max_length=60)
    jmldana = models.IntegerField()
    ceritasingkat = models.TextField(max_length=150)
    
class Display(models.Model):
    disp= models.ForeignKey(Formulir, on_delete=models.CASCADE)

penerima/forms.py
from django import forms
from .models import Formulir
class PendaftaranForm(forms.ModelForm):
      class Meta:
        model = Formulir
        fields ='__all__'
        labels = {
          'namalengkap':('Nama Lengkap'),
          'email':('Email'),
          'pekerjaan':('Pekerjaan'),
          'kota':('Kota'),
          'jmldana':('Jumlah Dana'),
          'ceritasingkat':('Cerita Singkat'),
        }
        placeholder= {
          
        }

penerima/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render,redirect
from main.views import User

from .forms import PendaftaranForm
from .models import Formulir, Display
from main.views import User
# Create your views here.

def pendaftar(request):

    return render(request, 'form/pendaftar.html')
def thanks(request):
    return render(request, 'form/terimakasih.html')



#DIsini cek lagi kyknya msih salah!!!##
def pendaftar_form(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = PendaftaranForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            daftar= Formulir()
            daftar.namalengkap=form.cleaned_data['namalengkap']
            daftar.email=form.cleaned_data['email']
            daftar.pekerjaan=form.cleaned_data['pekerjaan']
            daftar.kota=form.cleaned_data['kota']
            daftar.jmldana=form.cleaned_data['jmldana']
            daftar.ceritasingkat=form.cleaned_data['ceritasingkat']
            daftar.save(True)
            # redirect to a new URL:
        return redirect('terimakasih/')

        

    # if a GET (or any other method) we'll create a blank form
    else:
        pdft= Formulir.objects.all()
        form = PendaftaranForm()
        response = {"formulir-pendaftar":pdft, 'form':form}
        return render(request, 'form/pendaftar.html',response)

def display_form(request):
    form= Formulir.objects.all()
    response={'form':form}
    return render(request, 'form/displaypenerima.html', response)

penerima/templates/form/displaypenerima.html
{% extends "base.html" %}
{% load static %}
{% block meta %}
  <title>CROWD-VID | DONATUR</title>
{% endblock meta %}
{% block content %}
<div class="container contentform" style="padding-left: 25px; padding-right: 25px;">
    <h1 class="green3"><br>Mereka butuh bantuan finansialmu!</h1>
    {% if form %}
        {% for formulir in form %}
            <div class="card m-5" style="padding: 20px; border-radius: 30px;">
                <tr>
                    <h1><a class="green2" style="text-decoration:none" href="{% url 'donatur:formulir_donatur' %}">{{formulir.namalengkap}}</a></h1>
                    <p class="green2">{{formulir.email}} <br> {{formulir.pekerjaan}}, {{formulir.kota}}</p>
                
                    <p class="grey">{{formulir.ceritasingkat}}</p>
                    <p class="green2">Rp. {{formulir.jmldana}}</p>
                </tr>
            </div>
        {% endfor %}
    {% endif %}
    <br>
</div>
{% endblock content %}

penerima/templates/form/pendaftar.html
{% load static %}
{% include "navbar.html" %}
<html>
        <head>
            <title>CROWD-VID | FORM PENERIMA</title>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
            <link rel="stylesheet" href="{% static 'css/style.css' %}">
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
            <script src="static https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
            <style>
                @import url('https://fonts.googleapis.com/css?family=Days+One&display=swap');
                @import url('https://fonts.googleapis.com/css?family=Montserrat&display=swap');

                .site-form input, .site-form textarea{
                    display: block;
                    font-family: 'Montserrat';
                    width: 100%;
                    border: 0px;
                    padding-inline-end: 10px;
                }

            </style>
        </head>


    <body>
        <div class = "container contentform">
        <div class= "row" style="padding: 25px;">
            {% if user.is_authenticated %}
            <div>
                <h1 class="green3">Peraturan</h1>
                <br>
                <p class="white" style="text-align: justify; font-family: Montserrat;">Crowdvid merupakan platform 
                    crowdfunding yang dikhususkan bagi mereka yang
                     <b>terkena dampak ekonomi dari pandemi</b></p>
                <br> 
                <p class="white" style="text-align: justify; font-family: Montserrat;">Harap masukkan data yang valid agar kami bisa membantu kamu!</p>
                <br>
                <h1 class="green3">Lengkapi data di bawah ini</h1>
               <form class="site-form" action="" method="POST">
                   <div class="green3">
                        {% csrf_token %}
                        {{ form }}
                    </div>
               
                    <br>
                    <input type = "submit" value="SELESAI" class="btn ma">
                    
                   
                     
                </form>
                {% else %}
                <p> maaf, anda harus login terlebih dahulu sebelum menggunakan fitur form donatur</p>
                <p><a href="{% url 'main:login' %}">Klik di sini untuk login</a></p>
                <br>
                {% endif %}
            </div>

        </div>
        </div>

    </body>
    {% include "footer.html" %}

</html>

penerima/templates/form/terimakasih.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<head>
    <title> TERIMA KASIH! </title>
</head>
<h1 class="green1 tks">Terima Kasih!</h1>
<p class="green2 tks2">
    Bantuan finansial kamu akan segera kamu dapat dalam waktu dekat.
    <br> Jangan lupa untuk selalu <b>#PeduliSesama</b> !
</p>

{% endblock content %}