TugasKelompok_1/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('formulir/', include('donatur.urls')),
    path('penerima/', include('penerima.urls')),
    path('kritik-saran/', include('kritiksaran.urls')),
    path('testimoni/',include('testimoni.urls')),
   
]

kritiksaran/urls.py
from django.urls import path

from . import views


app_name = 'kritiksaran'

urlpatterns = [
    path('', views.display_kritik_saran, name='display_kritik_saran'),
    path('form-kritik-saran/', views.form_kritik_saran, name='form_kritik_saran'),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.log_in, name='login'),
    path('logout/', views.log_out, name='logout'),
    path('signup/', views.signup, name='signup'),

]

kritiksaran/models.py
from django.db import models

# Create your models here.
class FormKritikSaran(models.Model):
    namainitial= models.CharField(max_length=60)
    kritik = models.TextField(max_length=150)
    saran= models.TextField(max_length=150)
    
class Tampilan(models.Model):
    tampilan=models.ForeignKey(FormKritikSaran, on_delete=models.CASCADE)

kritiksaran/forms.py
from django import forms
from .models import FormKritikSaran
class FormulirKritikSaran(forms.ModelForm):
    class Meta:
        model = FormKritikSaran
        fields ='__all__'
        labels = {
            'namainitial':('Nama Initial'),
            'kritik':('Kritik'),
            'saran': ('Saran'),
            
        }
    

kritiksaran/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render,redirect

from .forms import FormulirKritikSaran
from .models import FormKritikSaran, Tampilan
from main.views import User
# Create your views here.


def form_kritik_saran(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = FormulirKritikSaran(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            daftar= FormKritikSaran()
            daftar.namainitial=form.cleaned_data['namainitial']
            daftar.kritik=form.cleaned_data['kritik']
            daftar.saran=form.cleaned_data['saran']        
            daftar.save(True)
            # redirect to a new URL:
        return redirect('/kritik-saran') 

    # if a GET (or any other method) we'll create a blank form
    else:
        masukan= FormKritikSaran.objects.all()
        form = FormulirKritikSaran()
        response = {"masukan":masukan, 'form':form}
        return render(request, 'formkritiksaran.html',response)

def display_kritik_saran(request):
    form= FormKritikSaran.objects.all()
    response={'form':form}
    return render(request, 'displaykritiksaran.html', response)

kritiksaran/templates/displaykritiksaran.html
{% extends "base.html" %}
{% load static %}
{% block meta %}
  <title>CROWD-VID | KRITIK & SARAN</title>
{% endblock meta %}
{% block content %}
<div class="container contentform" style="padding-left: 25px; padding-right: 25px;">
    
    <h1 class="green3"><br>Kritik dan Saran</h1>
    <h5 class="white" style="text-align: justify;"><br>Kami masih dalam masa perkembangan, bantu kami menjadi lebih baik dengan kritik dan saranmu! Semudah <a class="green3" style="color: #61897F;" href="{% url 'kritiksaran:form_kritik_saran' %}">klik disini</a></h5>

    {% if form %}
        {% for formulir in form %}
            <div class="card m-5" style="padding: 20px; border-radius: 30px;">
                <tr>
                   <img src="{% static '{{formulir.img}}' %}" alt="">
                    <h1 class="green2">{{formulir.namainitial}}</h1>
                    <p class="green2">{{formulir.kritik}}</p>                
                    <p class="grey">{{formulir.saran}}</p>
                </tr>
            </div>
        {% endfor %}
    {% endif %}
    <br>
</div>
{% endblock content %}

kritiksaran/templates/formkritiksaran.html
{% extends "base.html" %}
{% load static %}
{% block meta %}
  <title>CROWD-VID | KRITIK & SARAN</title>
{% endblock meta %}
{% block content %}

<div class="container contentform">
    <div class="container">
        <br>
        <h1 class="green3">Kritik & Saran</h1><br>
        {% if user.is_authenticated %}

            <form class="site-form" action="" method="POST">
                <div class="green3">
                    {% csrf_token %}
                    {{ form }}
                </div>
                <div class = "centre-items" style = "margin-top: 2%">
                    <input type = "submit" class="btn center ma" style="color: white;" value="SELESAI"> 
                </div>
            </form><br>
        {% else %}
            <p> maaf, anda harus login terlebih dahulu sebelum menggunakan fitur ini</p>
            <p><a href="{% url 'main:login' %}">Klik di sini untuk login</a></p>
            <br>

        {% endif %}

    </div>
</div>

{% endblock content %}