TugasKelompok_1/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('formulir/', include('donatur.urls')),
    path('penerima/', include('penerima.urls')),
    path('kritik-saran/', include('kritiksaran.urls')),
    path('testimoni/',include('testimoni.urls')),
   
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.log_in, name='login'),
    path('logout/', views.log_out, name='logout'),
    path('signup/', views.signup, name='signup'),

]

penerima/urls.py
from django.urls import path

from . import views


app_name = 'penerima'

urlpatterns = [
    path('', views.pendaftar_form, name='pendaftar_form'),
    path('donatur/', views.display_form, name='display_form'),
    path('terimakasih/', views.thanks, name='thanks')
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% include "navbar.html" %}
  {% block content %}
  {% endblock content %}
  {% include "footer.html" %}
</body>

</html>

templates/footer.html
{% load static %}
<footer class="footer">
    <div class="row">
        <div class="col-9">
          <h1>Hubungi<br>Kami</h1>
        </div>
        <div class="col-3" style="text-align: left;">
          <p>Email : crowd@vid.id <br>
            Instagram : @crowdvid <br>
            Facebook : Crowdvid ID</p>
        </div>
      </div>
</footer>

templates/navbar.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link rel="stylesheet" type="text/css" href="style.css">

<style>
  @import url('https://fonts.googleapis.com/css?family=Days+One&display=swap');
   @import url('https://fonts.googleapis.com/css?family=Montserrat&display=swap');

.navbar {
  /* Rectangle 4 */
  position: relative;
  text-align: center;
  width: 100%;
  height: 10vw;
  left: 0px;
  top: 0px;
  background-color: #61897F;
}

.abc{
    /* PENERIMA & DONATUR*/

  font-family: Montserrat;
  font-style: normal;
  font-weight: normal;
  font-size: 3vw;
  text-align: center;
  color: #DFBEBE;
}

.abc:hover {
  color: #DFBEBE;
}

.navbar_right{
  position: absolute;
  right:4vw;
  float: right;
}

.navbar_left{
  position: absolute;
  text-align: left;
  left:4vw;
  float:none;
}

.crowdvid{
    /* CROWD-VID */

    position: relative;
    left: 18%;
    top: 0vw;

    font-family: Days One;
    font-style: normal;
    font-weight: normal;
    font-size: 4vw;
    display: inline;
    color: #DFBEBE;
}

.crowdvid:hover {
  color: #DFBEBE;
}

@media screen and (max-width: 1024px) {
  .crowdvid{
    left:10vw;
  }
  .navbar_left{
    left:3vw;
  }

@media screen and (max-width: 900px) {
  .crowdvid{
    left:13vw;
  }
  .navbar_left{
    left:-3vw;
  }
  .navbar_right{
    right:3vw;
  }

@media screen and (max-width: 700px) {
  .crowdvid{
    left:19vw;
  }
  .navbar_left{
    left:-3vw;
  }

  @media screen and (max-width: 450px) {
  .crowdvid{
    left:27vw;
  }
  .navbar_left{
    left:-3vw;
  }

  @media screen and (max-width: 300px) {
  .crowdvid{
    left:27vw;
  }
  .navbar_left{
    left:-3vw;
  }


 
}



</style>

<nav class="navbar" >
    <div class="container">
      <div class="navbar-header">
        <div class="row">
          <a class= "crowdvid col-sm" style="text-decoration:none" href="{% url 'main:home' %}"> CROWD-VID </a>
            <ul class="navbar_right">
              <a class="abc col-sm" style="text-decoration:none" href="{% url 'penerima:pendaftar_form' %}">PENERIMA</a>
            </ul>
            <ul class="navbar_left">
              <a class="abc col-sm" style="text-decoration:none" href="{% url 'penerima:display_form' %}">DONATUR</a>
            </ul>
        </div>

      </div>
    </div>
  </nav>