TugasKelompok_1/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('formulir/', include('donatur.urls')),
    path('penerima/', include('penerima.urls')),
    path('kritik-saran/', include('kritiksaran.urls')),
    path('testimoni/',include('testimoni.urls')),
   
]

kritiksaran/urls.py
from django.urls import path

from . import views


app_name = 'kritiksaran'

urlpatterns = [
    path('', views.display_kritik_saran, name='display_kritik_saran'),
    path('form-kritik-saran/', views.form_kritik_saran, name='form_kritik_saran'),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.log_in, name='login'),
    path('logout/', views.log_out, name='logout'),
    path('signup/', views.signup, name='signup'),

]

testimoni/urls.py
from django.urls import path
from . import views
from .views import *


app_name = "testimoni"

urlpatterns = [
    path('ulasan/', formulir_testimoni, name='testimoni'),
    path('', display_testimoni, name='d_testimoni'),
#     path('ulasan/',formulir_testimoni, name = 'testimoni'),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


def log_out(request):
    logout(request)
    return HttpResponseRedirect('/')
    
def home(request):
    return render(request, 'main/home.html')

def signup(request):
    if(request.method == "POST"):
        name = request.POST['username']
        email = request.POST['email']
        passs = request.POST['password']
        user = User.objects.create_user(name, email, passs)
        user.save()
        return HttpResponseRedirect('/login')
    else:
        return render(request, 'main/signup.html')


def log_in(request):
    if (request.method == "POST"):
        name = request.POST['username']
        passs = request.POST['password']
        user = authenticate(request, username=name, password=passs)
        success = False
        if user is not None:
            login(request, user)
            success = True
            return render(request, 'main/home.html', {'success':success})

        else:

            return render(request, 'main/login.html', {'success':success})
    else:  
        
        return render(request, 'main/login.html')

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>CROWDVID | HOME</title>
{% endblock meta %}

{% block style %}
<link rel="stylesheet" href="{% static 'style.css' %}">
{% endblock %}

{% block content %}
  <div class="contenthome">
    <div class="container mt-5">
      {% if user.is_authenticated %}
        Hai, {{user.username}}
        <a href="{% url 'main:logout' %}">log out</a>
      {% else %}
      Anda belum login, <a href="{% url 'main:login' %}">klik di sini untuk login</a>
      {% endif %}

      <div style="margin: auto;">
        <div class="row">
          <div class="box col-5 plspls magnify" style="padding: 10px;border-radius: 15px;">
            <h1 style="text-align: center;"><a class="green3" style="text-decoration:none; color: #61897F;" href="{% url 'kritiksaran:display_kritik_saran' %}">Kontribusi</a></h1>
            <p class="white" style="text-align: center;">Kritik dan Saran</p>
          </div>
          <div class="box col-5 plspls magnify" style="padding: 10px;border-radius: 15px;">
            <h1 style="text-align: center;"><a style="text-decoration:none; color: #61897F;" class="green3" href="{% url 'testimoni:d_testimoni' %}">Testimoni</a></h1>
            <p class="white" style="text-align: center;">Apa kata mereka?</p>
          </div>
        </div>
      </div>

      <br>

      <div>
        <h1 class="green1">#PeduliSesama</h1>
        <p class="green2">Di tengah situasi tak pasti COVID-19, kami harap dengan adanya platform ini dapat meningkatkan kesadaran masyarakat akan pentingnya <b>#PeduliSesama</b></p>
        <img class="responsive" src="{% static 'buruh.jpg' %}">
      </div>

      <!-- Box Infografis -->
      <div class="box magnify">
        <h1 class="white">Mengapa CrowdVid?</h1>
        <div class="row">
          <div class="col-3">
            <h1 class="redbig">35%</h1>
          </div>
          <div class="col" style="margin-left: 15px;margin-right: 15px;">
            <p class="white">Perusahaan terpaksa mengurangi jumlah pekerja alias <b>PHK untuk bertahan</b></p>
          </div>
        </div>
        <div class="row">
          <div class="col-3">
            <h1 class="redbig">50%</h1>
          </div>
          <div class="col" style="margin-left: 15px;margin-right: 15px;">
            <p class="white">Pekerja mengalami <b>pemotongan gaji sampai dengan 50%</b></p>
          </div>
        </div>
      </div>

      <br>

      <div>
        <h1 class="green1">Buruh Pabrik hingga Musisi</h1>
        <p class="green2">Beberapa sektor industri terkena dampak lebih besar dari pandemi ini. Ini kata mereka tentang <b>Crowdvid #PeduliSesama</b></p>
      </div>

      <!-- Testimoni -->
      <div class="row magnify" style="margin-top: 30px;">
        <div class="col">
          <img class="responsive" src="{% static 'photographer.png' %}">
        </div>
        <div class="col">
          <h3 class="green1">Salma, fotografer</h3>
          <p class="grey">hampir banget gabisa bayar kos karena job sepi, <b>untung ada crowdvid!</b> makasih buat semua yang udah kontribusi :-)</b></p>
        </div>
      </div>
      <div class="row magnify">
        <div class="col">
          <img class="responsive" src="{% static 'waiter.jpeg' %}">
        </div>
        <div class="col">
          <h3 class="green1">Agus, waiter</h3>
          <p class="grey">Bersyukur sekali karena Crowdvid saya sangat terbantu waktu restoran tutup dan belum gajian.</b></p>
        </div>
      </div>

      <div style="margin-top: 30px;">
        <h1 class="green3">Tunggu apa lagi?<br>Daftarkan dirimu langsung.</h1>
      </div>

    </div>
  </div>
{% endblock content %}

main/templates/main/login.html
{% extends 'base.html' %}

{% load static %}

{% block meta %}
<title>CROWDVID | Log In</title>
{% endblock meta %}

{% block style %}
<link rel="stylesheet" href="{% static 'style.css' %}">
{% endblock %}

{% block content %}
<div class="container contentform">
    <div class="container">
        <br>
        <form action="{% url 'main:login' %}" method="post">
            {% csrf_token %}
            <div class="form-container">
                <h1 class="green3">Log in</h2>   <br>
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                    <span class="input-group-text" id="basic-addon1"><i class="fa fa-user"></i></span>
                    </div>
                    <input type="text" class="form-control" placeholder="Username" name="username" id="username">
                </div>

                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1"><i class="fa fa-key"></i></span>
                    </div>
                    <input type="password" class="form-control" placeholder="Password" name="password" id="password">
                </div> <br>
                <input type = "submit" class="btn center ma" style="color: white;" value="LOG IN">
            {% if success == False %}
            <p style="color: red;">The credentials you are using are invalid</p>
            {% endif %}
            <p></p>
            <p>Don't have an account yet? <a href="{% url 'main:signup' %}">Sign Up</a></p>
            </div>
            <br>
        </form>
    </div>
</div>


{% endblock content %}

main/templates/main/signup.html
{% extends 'base.html' %}

{% load static %}

{% block meta %}
<title>CROWDVID | Log In</title>
{% endblock meta %}

{% block style %}
<link rel="stylesheet" href="{% static 'style.css' %}">
{% endblock %}

{% block content %}
<div class="container contentform">
    <div class="container">
        <br>
        <form action="{% url 'main:signup' %}" method="post">
            {% csrf_token %}
            <div class="form-container">
                <br>
                <h1 class="green3">Create Account</h2>  
                <br> 
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                    <span class="input-group-text" id="basic-addon1"><i class="fa fa-user"></i></span>
                    </div>
                    <input type="text" class="form-control" placeholder="Username" name="username" id="username"><br>
                </div>

                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                    <span class="input-group-text" id="basic-addon1"><i class="fa fa-at"></i></span>
                    </div>
                    <input type="email" class="form-control" placeholder="E-mail" name="email" id="email"><br>
                </div>

                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                    <span class="input-group-text" id="basic-addon1"><i class="fa fa-key"></i></span>
                    </div>
                    <input type="password" class="form-control" placeholder="Password" name="password" id="password"><br>
                </div>
                <br>
                <input type = "submit" class="btn center ma" style="color: white;" value="SIGN UP">

                <p></p>
                <p>Already have an account? <a href="{% url 'main:login' %}">Log in</a></p>
                <br>
            </div>
        </form>
    </div>
</div>
{% endblock content %}